---
name: Run tests and package firmware
on:
  push:
    branches:
    - '2.4'
    paths-ignore:
    - '**.md'
    - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches:
    - '2.4'
    paths-ignore:
    - '**.md'
    - '.github/ISSUE_TEMPLATE/**'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - T12
          - T16
          - T18
          - T8
          - TLITE
          - TX12
          - TX16S
          - X10
          - X12S
          - X7
          - X9D
          - X9DP
          - X9DP2019
          - X9LITE
          - XLITE
    container:
      image: ghcr.io/edgetx/edgetx-commit-tests
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          # fetch-depth: 0 # https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches

      - name: Test ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
        run: |
          echo "Running commit tests"
          ./tools/commit-tests.sh

      - name: Build ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
        run: |
          echo "Running firmware build"
          ./tools/build-gh.sh

      - name: Compose release filename
        # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
        run: echo "artifact_name=edgetx-firmware-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Package firmware ${{ matrix.target }}
        uses: 'actions/upload-artifact@v2'
        with:
          name: "${{ env.artifact_name }}"
          path: |
            fw.json
            LICENSE
            *.bin
          retention-days: 15
          if-no-files-found: error
